### ISSUE TITLE
*Error* load: can't access file - "$PDK_DIR/ncsu_basekit/cdssetup/display.drf"

### ISSUE THREAD

**Issue by saaditani** [LNIS-Projects/FreePDK45-RRAM-Addon#1]
Hello,
I am getting an error in Virtuoso messages:
*Error* load: can't access file - "$PDK_DIR/ncsu_basekit/cdssetup/display.drf"
*Error* load: error while loading file - "/opt/FreePDK45-RRAM-Addon/rram_addon/cdssetup/display_rram.drf" at line 2
*WARNING* Failed to Re-initialize drm.

I have given user rwx on the whole directory, any idea why?

also we are using VNC.

**Comment by egiacomin** [comment]
Resolved by email.
